Staff Assistance Requests
usnistgov/NEMO pull request #222
Opened 2024-05-08 01:07 UTC by abuckles-uci

Hello @rptmat57! This is the initial code for "staff assistance requests". It's essentially a duplicate of the buddy request system, but without needing to specify a start, end, or area. It is only a description of the issue the user wants assistance with. There's some more that I would like to add, however I would like to get your opinion if this is a good fit (and general code review).

* Allow staff to mark a request as "resolved", which essentially just hides the request and all its replies
* Restrict users to only see their own requests (only staff can see all the requests)

Thanks!
Aaron

Closes #186

2024-05-08 01:07 UTC, abuckles-uci commented
![image](https://github.com/usnistgov/NEMO/assets/135279879/3f8f6d5c-f192-48ec-bb4c-7ebeae491989)

2024-05-08 14:50 UTC, rptmat57 commented
Hi and thank you for this PR draft.
I like it and I think it would be a great addition to NEMO.

A few things:

1. Please follow the instructions for installing dev-tools and pre commit hooks: https://github.com/usnistgov/NEMO/wiki/Development-Setup#set-up-pre-commit-hooks and then run it on all the files so your changed files are formatted correctly
2. The staff assistance feature would need to be enabled explicitly, following the same idea as the customization "adjustment_requests_enabled"
3. There are a few copy-paste errors from the buddy view, so make sure to double check and also add new css classes for staff assistance.
4. You can remove the preference "email_new_staff_assistance_request_reply" since in this case the creator is the only user and he will always need to be notified

2024-05-08 15:37 UTC, abuckles-uci commented
Thank you for reviewing! I'll implement these changes

2024-05-09 00:06 UTC, abuckles-uci commented
Hi @rptmat57,

I've implemented the requested changes and finished up on adding a button to resolve requests. I made it so requests can only be resolved by staff and only if there is at least one reply. In addition, users can now only see their own requests, unless they are staff in which they see all.

The UI is pretty rough still, so I was hoping I could get some suggestions:
1. In the image below you can see that the top request scrolls to the right instead of wrapping. This is the same as the buddy systems. Should this be fixed?
2. I think it would be useful to filter out resolved requests. Currently I'm showing them with a [Resolved] badge below all unresolved requests.
3. I'm not totally sure how the notification system works, I haven't looked into it enough. I made the "expiration" 30 days like other requests, but I'm not sure if there's a better number for this.
4. On the same note as notifications, how does the email situation look? In my opinion it would be the requestor and all staff. In addition, how can I test emails locally? I was hoping I could get some assistance here.

Thanks!
Aaron

![image](https://github.com/usnistgov/NEMO/assets/135279879/147bf92a-2ee6-4af1-a000-50b9bd64362f)

2024-05-11 19:26 UTC, rptmat57 commented
Hi Aaron,

1. Yes, it should probably be fixed
2. I would have a separate section with resolved requests, a bit like we have for approved adjustment/area access requests
3. 30 days is good
4. Requestor and staff sounds good, you can test emails by going to Detailed administration -> Email logs

2024-05-23 01:41 UTC, rptmat57 commented on NEMO/views/notifications.py
> +    users: List[User] = User.objects.filter(is_active=True).exclude(id=staff_assistance_request.user_id)
you should limit to staff so other people don't get notified
```suggestion
    users: List[User] = User.objects.filter(is_active=True, is_staff=True).exclude(id=staff_assistance_request.user_id)
```

2024-05-23 21:11 UTC, abuckles-uci commented
Hi @rptmat57,

I committed your suggested change, so the notifications appear to be working as intended now.

For the emails, I added a new email that sends to _all staff_ when a staff assistance request is created. The replies still work the same (send to the request creator and other repliers). I have a couple of questions:

1. The replies use the `email_send_staff_assistance_request_replies` user preference. Do we want new staff assistance requests to use this same preference or always send to all staff?
2. Do we want an email to the request creator when their request is resolved/reopened?
3. I also hid the "New Request" button for staff, since this feature is meant for non-staff. Is this how you want it?

Thanks,
Aaron Buckles

2024-05-31 17:47 UTC, abuckles-uci commented
Hi @rptmat57,

Have you had a chance to review this PR yet?

Thanks,
Aaron Buckles

2024-05-31 20:39 UTC, rptmat57 requested changes
Thanks, it looks great! Outside of my inline comments, there are a few general changes I would like to request:

1. Please merge with 6.0.0.dev (there are new recent changes)
2. Also, I would prefer the notification (badge) for staff to only go away when the request is resolved
3. Lastly, when requests are resolved, let display them as a table (similar to adjustment requests, with replies smaller etc.)

2024-05-31 23:25 UTC, abuckles-uci commented
> Thanks, it looks great! Outside of my inline comments, there are a few general changes I would like to request:
> 
> 1. Please merge with 6.0.0.dev (there are new recent changes)
> 2. Also, I would prefer the notification (badge) for staff to only go away when the request is resolved
> 3. Lastly, when requests are resolved, let display them as a table (similar to adjustment requests, with replies smaller etc.)

Sounds good, thank you for the feedback. I'll work on implementing these sometime next week hopefully.

2024-06-10 17:12 UTC, abuckles-uci commented on NEMO/static/nemo.css
All merged

2024-06-10 17:55 UTC, abuckles-uci commented on NEMO/templates/requests/staff_assistance_requests/staff_assistance_request.html
Hi @rptmat57, do we still want to be able to edit the request after it has been sent?

2024-06-10 19:46 UTC, abuckles-uci commented
> Thanks, it looks great! Outside of my inline comments, there are a few general changes I would like to request:
> 
> 1. Please merge with 6.0.0.dev (there are new recent changes)
> 2. Also, I would prefer the notification (badge) for staff to only go away when the request is resolved
> 3. **Lastly, when requests are resolved, let display them as a table (similar to adjustment requests, with replies smaller etc.)**

Hi @rptmat57, how does this look?

![image](https://github.com/usnistgov/NEMO/assets/135279879/13a7abe7-57e4-4309-8766-4fd4fec69da0)

2024-06-12 00:00 UTC, abuckles-uci commented on NEMO/templates/requests/staff_assistance_requests/staff_assistance_request.html
Hi @rptmat57, I'm going to assume that editing is still wanted. I was able to come up with a UI for this. It utilizes the same modal as when creating a new request. I'm still working on implementing the backend logic.

![image](https://github.com/usnistgov/NEMO/assets/135279879/81b74489-2252-40b7-a085-ae3fd1bcad1a)

2024-06-12 00:06 UTC, abuckles-uci commented on NEMO/templates/requests/staff_assistance_requests/staff_assistance_request.html
Modal for a new request (same modal)

![image](https://github.com/usnistgov/NEMO/assets/135279879/63fb4424-c4ce-427d-974e-c7bcd3f02b6c)

2024-06-12 12:12 UTC, rptmat57 commented on NEMO/templates/requests/staff_assistance_requests/staff_assistance_request.html
> Hi @rptmat57, do we still want to be able to edit the request after it has been sent?

Yes, but only until someone replies. After there is a reply, the original should not be edited but rather new messages added as replies

2024-06-17 16:53 UTC, abuckles-uci commented
Hi @rptmat57,

I made the requested changes, so this should be ready to be reviewed again.

Thank,
Aaron

2024-06-17 18:01 UTC, rptmat57 commented
thanks, I'll try to take a look this week

2024-07-12 00:07 UTC, abuck351 commented
Hi @rptmat57, have you had a chance to review this PR yet? Thanks!

2024-08-13 21:39 UTC, abuck351 commented
Hi @rptmat57

Sorry to keep bumping this PR. Do you have any feedback? Thanks!

- Aaron

2024-09-12 20:21 UTC, abuckles-uci commented
Hi @rptmat57, 

Are there any updates for getting this pull request merged? Does anything need to be changed?

Thank you,
Aaron

2025-01-10 22:34 UTC, abuckles-uci commented
Hi @rptmat57,

What's the status of this pull request? I can make any changes needed to get this merged into 6.1, though it looks there weren't any merge conflicts.

Thank you,
Aaron Buckles

2025-02-04 02:42 UTC, rptmat57 commented
So sorry, I haven't forgotten about this, I intend to take a look this week

2025-02-04 16:50 UTC, abuckles-uci commented
Thank you!

2025-02-06 17:57 UTC, rptmat57 requested changes

2025-02-06 17:57 UTC, rptmat57 commented on NEMO/forms.py
> +
```suggestion
```

2025-02-06 17:57 UTC, rptmat57 commented on NEMO/migrations/0087_staff_assistance_requests.py
> +        ),
this shouldn't be needed anymore
```suggestion
```

2025-02-06 17:57 UTC, rptmat57 commented on NEMO/static/nemo.css
> +
what is this for?

2025-02-06 17:57 UTC, rptmat57 commented on NEMO/views/notifications.py
> +    expiration = datetime(staff_assistance_request.creation_time.year + 100, 1, 1)
let's just use the max
```suggestion
    expiration = datetime.max
```

2025-02-06 17:59 UTC, rptmat57 commented on NEMO/static/nemo.css
> +
```suggestion
```

2025-02-06 18:01 UTC, merged