Enable detail view of reservations
usnistgov/NEMO pull request #97
Opened 2021-12-16 04:09 UTC by jat255

Resolves #96 

@rptmat57 I'm sure there's a million things I could have done better, but this seems to be working for me. I'm more than happy to take any criticism or modifications. I think I got the title/project change and cancellation working too, although I may have hosed things up there, so I'd be happy for a review.

Here's what it looks like as staff or the user owning the reservation:
![image](https://user-images.githubusercontent.com/1278301/146306554-cf793524-216e-4b03-abf5-3138f5dd25d9.png)

And as a different user:
![image](https://user-images.githubusercontent.com/1278301/146306512-b45f1acd-40f2-4422-bf58-934ef8af5d27.png)

2021-12-16 15:22 UTC, jat255 commented
FYI, the only changes I made that could interact/interfere with other parts of the code were in [`change_reservation_project`](https://github.com/usnistgov/NEMO/pull/97/files#diff-1759e08770ec21c1991f35533a0710f8f94fa010fabaf04a0223317a04c4d32eR732-R757) of the `calendar.py` view. I noticed that regardless of what happens when you try to change the project, it was returning a 200, so it looked like it succeeded. I just added some condition checks to return various 40X codes if the project could not be changed.

2021-12-16 17:53 UTC, rptmat57 commented
That was quick!
I really like the look of your reservation details table!

Now for my (very detailed) feedback:

1. We use a limit of 120 characters in .py files NEMO, if you could change that, that'd be great. see https://github.com/usnistgov/NEMO/wiki/Contributions (also run the tests just in case)
2. I would really prefer not to duplicate the reservation details page. Otherwise every time we make a change in the future, we'll have to remember to change it in 2 separate places. That being said, it makes things a bit tricky with the popup and the cancelling etc.

I thought about it a bit, and I think I have an idea on how to make this work. 
A lot of this comes from anticipating similar needs in the future for usage events and other detail views.

I basically want to have a popup template, and be able to use either the full page or the popup template based on a given request parameter. i.e. `http://nemo.nist.gov/event_details/reservation/1/` -> full page, `http://nemo.nist.gov/event_details/reservation/1/?popup_view=true` -> popup

I realize this is slightly outside of the scope of this feature, but if you are open to it, here is what I propose:

1. Change the original reservation details page with your styling (because I like it). and make sure it looks good in the popup.
2. Add a `popup.html` template in `templates/base` folder with the following code:
```
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">{% block title %}{% endblock %}</h4>
</div>
<div class="modal-body">
    {% block content %}{% endblock %}
</div>
```
3. At the top of the reservation_details page, add `{% extends popup_view|yesno:"base/popup.html,base.html" %}`
4. Move the current `reservation_details` function from `calendar.py` into your `details.py` 
5. Rename the file `event_details.py`
6. Move the current reservation details url in `urls.py` to a separate section called `# Event details` right after the `# Calendar` section
7. Change the reservation details function to get a `popup_view` from the request: `popup_view = request.GET.get("popup_view")` and pass it to the template.
8. In `reservation_event_feed.html`, `specific_user_feed.html` and `usage_event_feed.html` change `"{% url 'reservation_details' x.id %}"` to `"{% url 'reservation_details' x.id %}?popup_view=true"`
8. Move the `templates/calendar/reservation_details.html` file to a new folder `templates/event_details/reservation_details.html`
9. Finally, if you want the change title, etc. functions to work, add the js in reservation_details.html with an `{% if not popup_view %}` otherwise change the conditions to only editing if `not popup_view`. I can go either way with having that functionality in there or not.
10. Make sure everything works (I didn't test any of it)

If realize it's a lot, so it's also totally fine if you just do 1) and I'll do the rest.

2021-12-17 02:13 UTC, jat255 commented
Ok, I believe I've implemented everything you suggested, as well as changing how the reservation question groups are implemented in the template (I did it using a `templatetag`, since it was easier for me to do in Python than in the Django template language). 

There are two remaining issues/things I wanted to point out:

- if viewing details from a modal, and you do something that fails (trying to change project of a past reservation, for example); the modal response from the failed callback doesn't show up until the first modal is closed (since you can only have one modal open at a time...)
- to make the the new table design fit in the modal, I had to make the modal "large" size. This is done by adding `modal-lg` to the `modal-dialog` class, but this is set in the base template, which means all modals will now be `modal-lg` (unless we pulled this out into the `popup.html`, maybe). If this is a problem, we should refactor it a bit

2021-12-17 15:45 UTC, rptmat57 commented
adding the "data-dismiss" attribute on the buttons takes care of the issue with the new popup not appearing.

for the large popup, I'll take care of it. I would prefer it only be large for this, since all error messages etc. look a bit silly in the big version

2021-12-17 15:52 UTC, jat255 commented
Ok, cool. Let me know if you need any changes from me. You should be able to push to my branch directly, I think

2021-12-17 15:52 UTC, rptmat57 requested changes
alright if you can address those things that should do it.
I'll fix the popup size separately
thanks! sorry this got a bit crazy

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templatetags/custom_tags_and_filters.py
> +							mark_safe(header_cells))
```suggestion
	head_html = format_html('<thead><tr><th>#</th>{}</tr></thead>', mark_safe(header_cells))
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templatetags/custom_tags_and_filters.py
> +							   mark_safe(data_cells_html))
```suggestion
		row_html = format_html('<tr><th>{}</th>{}</tr>', i + 1, mark_safe(data_cells_html))
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +                    <button type="button" class="btn btn-success"
```suggestion
                    <button type="button" class="btn btn-success" data-dismiss="modal"
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +                            <button type="button" class="btn btn-success" onclick="{% if popup_view %}$('#dialog').one('hidden.bs.modal', function() { {% endif %} change_reservation_project('{% url '
```suggestion
                            <button type="button" class="btn btn-success" data-dismiss="modal" onclick="{% if popup_view %}$('#dialog').one('hidden.bs.modal', function() { {% endif %} change_reservation_project('{% url 'change_reservation_project' reservation.id %}', $('#change_project').val()) {% if popup_view %} }) {% endif %}">Change project</button>
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +        <td>
```suggestion
        <td style="padding: 0;">
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +            <table class="table table-striped">
```suggestion
            <table class="table table-striped" style="margin-bottom: 0;">
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +                            <table class="table table-striped">
```suggestion
                            <table class="table table-striped" style="margin-bottom: 0;">
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +                        <td>{{ data.title }}{% if data.title|slice:"-1:" != ":" %}:{% endif %}</td>
```suggestion
                        <td {% if forloop.first %}style="border-top:none;"{% endif %}>{{ data.title }}{% if data.title|slice:"-1:" != ":" %}:{% endif %}</td>
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +                        <td>
```suggestion
                        <td style="padding: 0;{% if forloop.first %}border-top:none;{% endif %}">
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +                        <td>{{ data.title }}{% if data.title|slice:"-1:" != ":" %}:{% endif %}</td>
```suggestion
                        <td {% if forloop.first %}style="border-top:none;"{% endif %}>{{ data.title }}{% if data.title|slice:"-1:" != ":" %}:{% endif %}</td>
```

2021-12-17 15:52 UTC, rptmat57 commented on NEMO/templates/event_details/reservation_details.html
> +                        <td>{{ data.user_input|linebreaksbr }}</td>
```suggestion
                        <td {% if forloop.first %}style="border-top:none;"{% endif %}>{{ data.user_input|linebreaksbr }}</td>
```

2021-12-17 15:54 UTC, jat255 commented
Oh, I see your comments now. I'll take care of those shortly

2021-12-17 15:57 UTC, rptmat57 commented
most of them can be pushed directly from the suggestions.
there is a couple more that you'll need to address

2021-12-17 17:28 UTC, jat255 reviewed
These were addressed in a separate comment (I didn't feel comfortable with knowing how to do it directly from Github, so sorry if that messed up the code-review process)

2021-12-17 19:54 UTC, rptmat57 approved these changes
all good, thanks for being accommodating!!

2021-12-17 20:16 UTC, merged